# sync_with_choice.yaml
blueprint:
  name: "Синхронизация с выбором действия"
  description: "Гибкий шаблон: реакция на событие с выбором команды"
  domain: automation
  author: "Helper"
  input:
    trigger_entity:
      name: "🔘 Устройство-триггер"
      selector:
        entity:
    trigger_state:
      name: "🎯 Состояние триггера"
      default: "off"
      selector:
        select:
          options:
            - "on"
            - "off"
    target_entity:
      name: "💡 Целевое устройство"
      selector:
        entity:
    action_type:
      name: "⚙️ Действие"
      default: "turn_off"
      selector:
        select:
          options:
            - label: "Включить"
              value: "turn_on"
            - label: "Выключить"
              value: "turn_off"
            - label: "Переключить"
              value: "toggle"

trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: !input trigger_state

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ input('action_type') == 'turn_on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input target_entity
      - conditions:
          - condition: template
            value_template: "{{ input('action_type') == 'turn_off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input target_entity
    default:
      - service: homeassistant.toggle
        target:
          entity_id: !input target_entity

mode: single
